import { format } from "date-fns";

import type { KanbanState } from "./types";

const today = new Date();
const dateAfter = (days: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + days);
  return format(date, "yyyy-MM-dd");
};
const createdAt = new Date().toISOString();

export const initialKanbanState: KanbanState = {
  projects: [
    {
      id: "project-product-launch",
      name: "Product launch",
      description: "Everything needed for a calm, confident release.",
      color: "#3b82f6",
      position: 0,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "project-home",
      name: "Home refresh",
      description: "Small improvements that make home feel better.",
      color: "#14b8a6",
      position: 1,
      createdAt,
      updatedAt: createdAt,
    },
  ],
  columns: [
    {
      id: "launch-backlog",
      projectId: "project-product-launch",
      name: "Backlog",
      color: "#64748b",
      position: 0,
      wipLimit: null,
      isDone: false,
    },
    {
      id: "launch-progress",
      projectId: "project-product-launch",
      name: "In progress",
      color: "#3b82f6",
      position: 1,
      wipLimit: 4,
      isDone: false,
    },
    {
      id: "launch-review",
      projectId: "project-product-launch",
      name: "Review",
      color: "#8b5cf6",
      position: 2,
      wipLimit: 3,
      isDone: false,
    },
    {
      id: "launch-done",
      projectId: "project-product-launch",
      name: "Done",
      color: "#10b981",
      position: 3,
      wipLimit: null,
      isDone: true,
    },
    {
      id: "home-ideas",
      projectId: "project-home",
      name: "Ideas",
      color: "#64748b",
      position: 0,
      wipLimit: null,
      isDone: false,
    },
    {
      id: "home-next",
      projectId: "project-home",
      name: "Up next",
      color: "#f59e0b",
      position: 1,
      wipLimit: 3,
      isDone: false,
    },
    {
      id: "home-doing",
      projectId: "project-home",
      name: "Doing",
      color: "#14b8a6",
      position: 2,
      wipLimit: 2,
      isDone: false,
    },
    {
      id: "home-done",
      projectId: "project-home",
      name: "Done",
      color: "#10b981",
      position: 3,
      wipLimit: null,
      isDone: true,
    },
  ],
  labels: [
    {
      id: "label-launch",
      projectId: "project-product-launch",
      name: "Launch",
      color: "#f43f5e",
      position: 0,
    },
    {
      id: "label-design",
      projectId: "project-product-launch",
      name: "Design",
      color: "#8b5cf6",
      position: 1,
    },
    {
      id: "label-copy",
      projectId: "project-product-launch",
      name: "Copy",
      color: "#0ea5e9",
      position: 2,
    },
    {
      id: "label-research",
      projectId: "project-product-launch",
      name: "Research",
      color: "#f59e0b",
      position: 3,
    },
    {
      id: "label-home-shopping",
      projectId: "project-home",
      name: "Shopping",
      color: "#f59e0b",
      position: 0,
    },
    {
      id: "label-home-weekend",
      projectId: "project-home",
      name: "Weekend",
      color: "#14b8a6",
      position: 1,
    },
  ],
  cards: [
    {
      id: "card-launch-plan",
      projectId: "project-product-launch",
      columnId: "launch-backlog",
      title: "Write the launch day runbook",
      description:
        "Capture owners, timing, fallback plans, and the exact order of release steps.",
      priority: "high",
      dueDate: dateAfter(5),
      labelIds: ["label-launch"],
      position: 0,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "card-feedback",
      projectId: "project-product-launch",
      columnId: "launch-backlog",
      title: "Collect beta feedback themes",
      description: "Turn individual comments into a short list of repeated patterns.",
      priority: "medium",
      dueDate: dateAfter(3),
      labelIds: ["label-research"],
      position: 1,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "card-onboarding",
      projectId: "project-product-launch",
      columnId: "launch-progress",
      title: "Polish first-run onboarding",
      description: "Reduce the setup to the three decisions that actually matter.",
      priority: "urgent",
      dueDate: dateAfter(1),
      labelIds: ["label-design", "label-launch"],
      position: 0,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "card-release-notes",
      projectId: "project-product-launch",
      columnId: "launch-progress",
      title: "Draft release notes",
      description: "Lead with outcomes, then cover the smaller improvements.",
      priority: "medium",
      dueDate: dateAfter(2),
      labelIds: ["label-copy"],
      position: 1,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "card-pricing",
      projectId: "project-product-launch",
      columnId: "launch-review",
      title: "Final pricing page review",
      description: "Check mobile layout, plan names, and every purchase path.",
      priority: "high",
      dueDate: dateAfter(0),
      labelIds: ["label-design", "label-copy"],
      position: 0,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "card-domain",
      projectId: "project-product-launch",
      columnId: "launch-done",
      title: "Configure production domain",
      description: "",
      priority: "high",
      dueDate: dateAfter(-1),
      labelIds: ["label-launch"],
      position: 0,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "card-entryway",
      projectId: "project-home",
      columnId: "home-ideas",
      title: "Sketch a calmer entryway",
      description: "Hooks, a narrow bench, and one place for keys.",
      priority: "low",
      dueDate: null,
      labelIds: [],
      position: 0,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "card-lamp",
      projectId: "project-home",
      columnId: "home-next",
      title: "Choose a reading lamp",
      description: "Warm light, adjustable arm, no visible cable if possible.",
      priority: "medium",
      dueDate: dateAfter(8),
      labelIds: ["label-home-shopping"],
      position: 0,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "card-shelves",
      projectId: "project-home",
      columnId: "home-doing",
      title: "Mount the office shelves",
      description: "Measure twice. Use the longer wall plugs.",
      priority: "high",
      dueDate: dateAfter(2),
      labelIds: ["label-home-weekend"],
      position: 0,
      createdAt,
      updatedAt: createdAt,
    },
  ],
};
