import { readFile, rename, writeFile } from "node:fs/promises";
import { createInterface } from "node:readline/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

import { parse } from "dotenv";

export const projectRoot = fileURLToPath(new URL("../..", import.meta.url));
export const desktopConfigPath = path.join(
  projectRoot,
  ".env.desktop.local",
);

const repositoryEnvPath = path.join(projectRoot, ".env");
const defaultApiUrl = "http://localhost:8787";

async function readEnvironmentFile(filePath) {
  try {
    return parse(await readFile(filePath));
  } catch (error) {
    if (error?.code === "ENOENT") return {};
    throw error;
  }
}

function normalizeApiUrl(value) {
  let url;
  try {
    url = new URL(value);
  } catch {
    throw new Error(`Invalid API URL: ${value}`);
  }

  if (!["http:", "https:"].includes(url.protocol)) {
    throw new Error("The desktop API URL must use http or https.");
  }
  if (url.username || url.password) {
    throw new Error("The desktop API URL cannot contain credentials.");
  }
  if (url.pathname !== "/" || url.search || url.hash) {
    throw new Error(
      "Use only the API origin, for example https://api.lifever.app.",
    );
  }

  return url.origin;
}

async function askForApiUrl() {
  const prompt = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log(
    "\nLifever desktop needs the public URL of the API it should use.",
  );
  console.log(
    "This is client configuration, not a database or authentication secret.",
  );
  const answer = await prompt.question(`API URL [${defaultApiUrl}]: `);
  prompt.close();
  return answer.trim() || defaultApiUrl;
}

async function writeDesktopConfig(apiUrl) {
  const temporaryPath = `${desktopConfigPath}.${process.pid}.tmp`;
  const contents = [
    "# Generated by pnpm desktop:configure.",
    "# Public desktop client configuration only; backend secrets stay in .env.",
    `VITE_API_URL="${apiUrl}"`,
    "",
  ].join("\n");

  await writeFile(temporaryPath, contents, { mode: 0o600 });
  await rename(temporaryPath, desktopConfigPath);
}

export async function ensureDesktopConfig({
  requestedApiUrl,
  interactive = Boolean(process.stdin.isTTY && process.stdout.isTTY),
} = {}) {
  const [desktopEnvironment, repositoryEnvironment] = await Promise.all([
    readEnvironmentFile(desktopConfigPath),
    readEnvironmentFile(repositoryEnvPath),
  ]);
  const configuredApiUrl =
    requestedApiUrl ??
    process.env.VITE_API_URL ??
    desktopEnvironment.VITE_API_URL ??
    repositoryEnvironment.VITE_API_URL;
  const apiUrl = normalizeApiUrl(
    configuredApiUrl ??
      (interactive ? await askForApiUrl() : defaultApiUrl),
  );

  if (desktopEnvironment.VITE_API_URL !== apiUrl) {
    await writeDesktopConfig(apiUrl);
    console.log(`Saved desktop API configuration to ${desktopConfigPath}`);
  }

  return { apiUrl, configPath: desktopConfigPath };
}
