import {
  addDays,
  addMinutes,
  setCalendarTime,
  startOfLocalDay,
  startOfWeek,
  subDays,
} from "../lib/dates";
import { categoryIdForLegacyColor } from "../lib/categories";
import type { CalendarCollection, CalendarEvent } from "./types";

export const defaultLocalCalendars: CalendarCollection[] = [
  {
    id: "local-personal",
    name: "Personal",
    color: "#3B82F6",
    position: 0,
    visible: true,
    writable: true,
    source: "lifever",
    createdAt: new Date(0).toISOString(),
  },
];

const makeEvent = (
  id: string,
  title: string,
  date: Date,
  startHour: number,
  startMinute: number,
  durationMinutes: number,
  legacyColor: "blue" | "violet" | "orange" | "green" | "pink" | "red",
  location = "",
  notes = "",
): CalendarEvent => {
  const start = setCalendarTime(date, startHour, startMinute);
  const end = addMinutes(start, durationMinutes);
  return {
    id,
    title,
    startAt: start.toISOString(),
    endAt: end.toISOString(),
    categoryId: categoryIdForLegacyColor(legacyColor),
    calendarId: defaultLocalCalendars[0]!.id,
    location,
    notes,
    alertsEnabled: true,
    allDay: false,
    source: "lifever",
    readOnly: false,
    createdAt: subDays(start, 1).toISOString(),
  };
};

const makeAllDayEvent = (
  id: string,
  title: string,
  date: Date,
  durationDays: number,
  legacyColor: "blue" | "violet" | "orange" | "green" | "pink" | "red",
  notes = "",
): CalendarEvent => {
  const start = startOfLocalDay(date);
  const end = addDays(start, durationDays);
  return {
    id,
    title,
    startAt: start.toISOString(),
    endAt: end.toISOString(),
    categoryId: categoryIdForLegacyColor(legacyColor),
    calendarId: defaultLocalCalendars[0]!.id,
    location: "",
    notes,
    alertsEnabled: true,
    allDay: true,
    source: "lifever",
    readOnly: false,
    createdAt: subDays(start, 1).toISOString(),
  };
};

const today = new Date();
const monday = startOfWeek(today);
const day = (index: number) => addDays(monday, index);

export const initialCalendarEvents: CalendarEvent[] = [
  makeAllDayEvent(
    "launch-week",
    "Launch week",
    day(1),
    3,
    "pink",
    "Keep the release checklist moving across design, engineering, and launch.",
  ),
  makeEvent(
    "morning-walk",
    "Morning walk",
    day(0),
    6,
    45,
    45,
    "green",
    "Riverside",
  ),
  makeEvent(
    "weekly-planning",
    "Weekly planning",
    day(0),
    8,
    15,
    60,
    "pink",
    "Home office",
    "Set priorities, protect focus time, and review the week ahead.",
  ),
  makeEvent(
    "product-focus",
    "Product focus",
    day(0),
    10,
    15,
    120,
    "violet",
    "Studio",
    "Finish the calendar interactions and polish the weekly view.",
  ),
  makeEvent("monday-lunch", "Lunch break", day(0), 13, 0, 60, "orange", "Nolita"),
  makeEvent(
    "roadmap-review",
    "Roadmap review",
    day(0),
    15,
    0,
    75,
    "blue",
    "Video call",
    "Review the next release scope with the product team.",
  ),
  makeEvent("strength-training", "Strength training", day(0), 18, 0, 75, "green", "Gym"),
  makeEvent(
    "morning-admin",
    "Morning admin",
    day(1),
    7,
    30,
    60,
    "blue",
    "Home office",
    "Inbox, invoices, and the small tasks that unblock the day.",
  ),
  makeEvent(
    "deep-work",
    "Deep work",
    day(1),
    10,
    15,
    150,
    "violet",
    "Studio",
    "Protect this time for the hardest problem of the day.",
  ),
  makeEvent("lunch-ana", "Lunch with Ana", day(1), 13, 30, 75, "orange", "Bar Pacyfik"),
  makeEvent(
    "design-review",
    "Design critique",
    day(1),
    15,
    30,
    90,
    "pink",
    "Meet room",
    "Review the latest desktop flows and capture final polish notes.",
  ),
  makeEvent("dinner-kino", "Dinner at Kino", day(1), 19, 0, 105, "orange", "Kino"),
  makeEvent("morning-swim", "Morning swim", day(2), 6, 30, 60, "green", "Pool"),
  makeEvent("team-standup", "Team stand-up", day(2), 9, 0, 60, "blue", "Video call"),
  makeEvent(
    "project-kickoff",
    "Project kickoff",
    day(2),
    10,
    15,
    90,
    "red",
    "Workshop room",
    "Align on outcomes, owners, milestones, and the first working session.",
  ),
  makeEvent("dentist", "Dentist", day(2), 12, 30, 60, "green", "Mokotów"),
  makeEvent(
    "release-notes",
    "Write release notes",
    day(2),
    14,
    30,
    105,
    "violet",
    "Studio",
  ),
  makeEvent("evening-run", "Evening run", day(2), 18, 30, 75, "green", "Riverside"),
  makeEvent("coffee-inbox", "Coffee + inbox", day(3), 7, 15, 60, "orange", "Relaks"),
  makeEvent(
    "client-workshop",
    "Client workshop",
    day(3),
    10,
    15,
    120,
    "red",
    "Conference room",
    "Map the new workflow and agree on the launch checklist.",
  ),
  makeEvent("thursday-lunch", "Lunch break", day(3), 12, 45, 60, "orange", "Bibenda"),
  makeEvent(
    "build-prototype",
    "Build prototype",
    day(3),
    14,
    15,
    150,
    "violet",
    "Studio",
    "Turn the approved flow into a polished interactive prototype.",
  ),
  makeEvent("yoga", "Yoga", day(3), 18, 0, 75, "green", "Studio Saska"),
  makeEvent(
    "weekly-review",
    "Weekly review",
    day(4),
    8,
    15,
    75,
    "pink",
    "Home office",
    "Close open loops and write down the three most important wins.",
  ),
  makeEvent(
    "friday-mobility",
    "Mobility",
    day(4),
    6,
    45,
    45,
    "green",
    "Home",
  ),
  makeEvent("friday-focus", "Deep work", day(4), 10, 30, 120, "violet", "Studio"),
  makeEvent("friday-lunch", "Lunch with Marta", day(4), 13, 0, 75, "orange", "Charlotte"),
  makeEvent(
    "product-demo",
    "Product demo",
    day(4),
    15,
    0,
    90,
    "blue",
    "Video call",
    "Share the completed release and collect the final round of feedback.",
  ),
  makeEvent("plan-weekend", "Plan the weekend", day(4), 17, 30, 60, "pink"),
  makeEvent("long-run", "Long run", day(5), 7, 0, 105, "green", "Łazienki Park"),
  makeEvent("farmers-market", "Farmers market", day(5), 11, 30, 90, "orange", "Hala Mirowska"),
  makeEvent("read-recharge", "Read + recharge", day(5), 15, 0, 120, "violet", "Home"),
  makeEvent(
    "dinner-friends",
    "Dinner with friends",
    day(5),
    19,
    0,
    120,
    "orange",
    "Praga",
  ),
  makeEvent("slow-breakfast", "Slow breakfast", day(6), 8, 0, 90, "orange", "Home"),
  makeEvent(
    "weekly-reset",
    "Weekly reset",
    day(6),
    11,
    0,
    90,
    "pink",
    "Home",
    "Tidy up, review notes, and clear the decks for Monday.",
  ),
  makeEvent("park-walk", "Walk in the park", day(6), 14, 0, 90, "green", "Pole Mokotowskie"),
  makeEvent(
    "prep-next-week",
    "Prep next week",
    day(6),
    17,
    0,
    90,
    "blue",
    "Home office",
  ),
];
